name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    env:
      BYTEDANCE_APPID: ${{ secrets.BYTEDANCE_APPID }}
      BYTEDANCE_TOKEN: ${{ secrets.BYTEDANCE_TOKEN }}
      TEST_SPEAKER_ID: ${{ secrets.TEST_SPEAKER_ID }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio
        pip install -r requirements.txt
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pytest -v