name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio
        pip install -r requirements.txt
        pip install -e .
        pip install pyinstaller

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        pytest tests/test_config.py -v

    - name: Build macOS App
      run: |
        pyinstaller --name="Voice Clone" \
                   --windowed \
                   --onefile \
                   voice_clone_test.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: VoiceClone-macOS
        path: dist/*